spring.application.name: eurekaserver
server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:project.keystore
    key-store-type: PKCS12
    key-store-password: Pass1111
    key-alias: eurekaserver
    trust-store: classpath:project.keystore
    trust-store-type: PKCS12
    trust-store-password: Pass1111
eureka:
  server:
    my-url: https://localhost:8761/eureka/
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      enabled: true
      key-store: classpath:project.keystore
      key-store-password: Pass1111
      key-password: Pass1111
      key-store-type: PKCS12
      trust-store: classpath:project.keystore
      trust-store-password: Pass1111
      trust-store-type: PKCS12
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
